apiVersion: registry.apicur.io/v1
kind: ApicurioRegistry
metadata:
  name: service-registry
  namespace: service-registry
spec:
  configuration:
    persistence: sql
    sql:
      dataSource:
        password:
        url:
        userName:
  deployment:
    replicas: 3
