apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: postgres
spec:
  backups:
    pgbackrest:
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 2Gi
                  cpu: 500m
                  memory: 1Gi
              limits:
                cpu: 1
                memory: 4Gi
  instances:
    - dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
            cpu: 500m
            memory: 2Gi
          limits:
            cpu: 1
            memory: 4Gi
      name: instance1
      replicas: 3
  openshift: true
  port: 5432
  postgresVersion: 13
  users:
    - databases:
        - service-registry
      name: service-registry
