apiVersion: registry.apicur.io/v1
kind: ApicurioRegistry
metadata:
  name: service-registry
spec:
  configuration:
    persistence: sql
    sql:
      dataSource:
        password: "DB_PASSWORD"
        userName: "DB_USERNAME"
        url: "JDBC_URL"
  deployment:
    replicas: 3
