apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: keycloak
  labels:
    app: sso
spec:
  externalAccess:
    enabled: true
  keycloakDeploymentSpec:
    imagePullPolicy: Always
    experimental:
      env:
        - name: JAVA_TOOL_OPTIONS
          value: '-Dcom.redhat.fips=false'
  postgresDeploymentSpec:
    imagePullPolicy: Always
  instances: 1
